### ISSUE TITLE
how about also include github.com/hyperledger/fabric/protoutil

### ISSUE THREAD

**Issue by davidkhala** [hyperledger/fabric-protos-go#10]
It is a awesome direction that we split protobuf out from fabric itself. 
Meanwhie in second development, fabric-protos-go is used frequently along with powerful tool github.com/hyperledger/fabric/protoutil
Would you consider also migrate github.com/hyperledger/fabric/protoutil to somewhere in github.com/hyperledger/fabric-protos-go

**Comment by jt-nti** [comment]
Hi @davidkhala, it would definitely be nice to have some more easily consumed higher level tools separated out from Fabric. I've opened hyperledger/fabric#3786 to get some more discussion going since this repo is intended just for the generated bindings. Thanks, James
